version: '3.8'

name: access-code-map

services:
  mongodb:
    image: mongo:latest
    container_name: access-code-mongodb
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  server:
    image: ghcr.io/neilenns/access-code-map-server:neilenns-issue117
    links:
      - mongodb
    restart: always      
    ports:
      - 3001:3001
    environment:
      - JWT_SECRET=d8c8e9f7-4d8c-4b2a-9c5f-3d9c8e7a1c6f
      - REFRESH_TOKEN_SECRET=b7e6f5d3-6b2c-4c3d-9c8a-1d2e3f4c5b6a
      - SESSION_EXPIRY=900
      - REFRESH_TOKEN_EXPIRY=2592000
      - MONGO_DB_CONNECTION_STRING=mongodb://access-code-mongodb:27017
      - MONGO_DB_NAME=access-code-map
      - COOKIE_SECRET=a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d
      # This must be set to the domain and port of the *client*.
      - WHITELISTED_DOMAINS=http://localhost:3000
      - PORT=3001
    depends_on:
      - mongodb

  client:
    image: ghcr.io/neilenns/access-code-map-client:neilenns-issue117
    restart: always
    ports:
      - 3000:80
    environment:
      # This must be set to the domain and port of the *server*. Note https in front
      # to ensure it uses SSL when making server calls. Without this there will be
      # errors in the browser attempting to call the server via HTTP when the
      # client is HTTPS.
      - SERVER_URL=http://localhost:3001/
    depends_on:
      - server
